### ISSUE TITLE
Memory leaks in Mono > 5.8.0.127

### ISSUE THREAD

**Issue by adsbxchange** [vradarserver/vrs#11]
Any Mono > 5.8.0127 will use system ram until it runs out of o/s resources or gets to an amount of ram that makes VRS  no longer manage the heap (effectively zombies).

Working with mono devs, but need to make sure file descriptors and whatever objects are created are being recycled back to garbage collector in orderly fashion.

**Comment by vradarserver** [comment]
If you have the release build of VRS running under Mono or standard .NET under Windows, and that instance runs for months on end without exhausting RAM or some other resource, then the release build of VRS must be disposing of objects as it should. If it wasn't then it would eventually fail regardless of the version of Mono or .NET that it's running under.

I have an instance of the release build of VRS that runs continuously for weeks on end without a problem. Its RAM usage stays pretty much the same from start to finish, the number of handles allocated fluctuates within a small range. I am fairly confident that - at least for the configuration that I'm running with - the release build of VRS is not leaking RAM or handles.

So... if you find that you have two instances of the same build of VRS running the same configuration but under two different versions of Mono, and one instance runs out of RAM or handles while the other does not, then it's going to be one of those versions of Mono that's leaking RAM or not releasing handles.

**Comment by adsbxchange** [comment]
What version of Mono are you running and are you putting any load on it?

**Comment by adsbxchange** [comment]
https://forum.virtualradarserver.co.uk/viewtopic.php?f=7&t=1554&p=7400&hilit=mono+memory#p7400

Referenced here as well.

https://github.com/mono/mono/issues/7655

**Comment by vradarserver** [comment]
.NET is a managed environment. A managed program is not responsible for memory management or (except in some circumstances) O/S resource management. The runtime is entirely responsible for allocating and releasing RAM and it is almost entirely responsible for obtaining and releasing operating system resources.

The only requirement on the managed program is that it has to make sure that no references exist to objects that are no longer in use. While references exist the runtime will not release the RAM or resources held by those objects, but once the references no longer exist - i.e. the objects go out of scope - then the memory and resources held by the objects can be released.

The release of RAM and resources when an object goes out of scope is not deterministic. It'll happen at some point but it won't happen as soon as the object goes out of scope. To give the program more control .NET has a mechanism for the deterministic release of resources (but not RAM - RAM is released non-deterministically). Objects that implement IDisposable can optionally release their resources as soon as Dispose() is called, obviously while a reference is still held to the object but usually just before the reference goes away. VRS takes advantage of the IDisposable interface where available. However, it's not mandatory to call Dispose on IDisposable objects. The mandatory responsibility on the program is only to make sure you don't hold references to objects that are no longer in use. That's all. If you don't call Dispose on IDisposable objects then the resources will still be released by the finaliser, they just go away whenever the garbage collector gets around to calling the finaliser. It will probably take longer before it happens. But it'll still happen at some point. The only requirement is that you do not hold references to dead objects, regardless of whether they implement IDisposable or not.

There is another requirement that the program has to fulfil if it uses unmanaged resources, which is that at a minimum it has to guarantee that the object's finaliser will release the unmanaged resource. You'd normally also have the object implement IDisposable and release the unmanaged resource in the Dispose() method. However, this is not a concern for VRS because it does not use unmanaged resources. All resources are accessed via the framework / runtime.

So. Under .NET there is no leak of RAM, there is no leak of resources, therefore no references are being held to objects that are no longer in scope. If references were being held after objects go out of scope then you'd have leaks under .NET.

The Mono runtime has to make the same guarantees about managing memory and resources on behalf of the managed application that the .NET runtime makes. That is the *whole point* of having a managed environment. It doesn't matter if the runtime is Mono or .NET, the runtime should work the same way. In particular the program relies on the runtime to release RAM and resources because it has absolutely no control over any of that, aside from the requirement about not holding references to dead objects (and releasing unmanaged resources, which isn't applicable here).

If the managed program runs without leaking RAM or resources on version X of Mono, and then leaks RAM or resources when running under version Y of Mono, then version Y of Mono is leaking. If you are saying that VRS runs without leaking on version 5.7 but then leaks on 5.8 then it is not VRS that is leaking when running under 5.8. It is Mono 5.8 that is leaking. The runtime is responsible for releasing RAM and resources. RAM and resource management is the raison d'etre of a managed environment. It is what the "managed" bit is referring to.

There is nothing, or almost nothing, that the managed program can do if the runtime leaks. The best it can do is try to work around the problem in the runtime, which is the tail wagging the dog. Five years from now that workaround would still be in the code tying to fix a problem that no longer exists.

**Comment by adsbxchange** [comment]
While you are not wrong, the leak exists and is therefor an issue.  Most Raspbian/ Debian distributions are using 4.6.2, once they push to the more recent stables - there is going to be a flood of bug reports for this memory leak.

Many people are running VRS on Pi. As referenced, Linux handles the ram consumption better than Windows, but none the less proves to be unstable.

5.8.0.127 is the last stable mono for VRS.  Prior to this the performance of mono is somewhat lacking compared to .NET.

VRS will also take down a Windows Server 2008 VM with copious amounts of RAM and CPU when placed under load.  To be usable for more that a few hours it requires forcing VRS to specific cores using affinity then leaving one core 'free' for Windows to prevent total lock up of the server.

There are also thread crashes under heavy load, but I suspect that is more related to Mono.
