### ISSUE TITLE
CentOS 8, Mono v.6.10 not loading aircraft markers

### ISSUE THREAD

**Issue by dan-christensen** [vradarserver/vrs#25]
The aircraft markers on the map aren't loading. I don't know if it's a mono thing, a VRS thing, or just a bad config. The server is creating the right folders and .png's but they're all empty images.
![Capture](https://user-images.githubusercontent.com/14892671/73766164-dd99c300-4732-11ea-8450-e9dae6feec50.PNG)

**Comment by dan-christensen** [comment]
Upgrading to Preview v.3 fixed this issue. Leaving open because I don't know if this is a known issue.

**Comment by dan-christensen** [comment]
Try using the stable release, or downgrading the beta.

**Comment by SJO-8164** [comment]
I have tried downgrading to stable release version 2.4.4 and PNG markers were still being incorrectly served as empty images.

Perhaps this is an issue with Mono 6?

I believe that version 2.4.4 only has support for PNG markers whereas the version 3 beta has additional support for SVG markers. Maybe when you upgraded to the version 3 beta, you started being served SVG markers instead of the broken PNG markers, giving the illusion that the upgrade fixed the issue.

Are you able to verify whether you have SVG markers enabled in your settings, and if they are enabled, does disabling them show the broken PNG markers once again? This would help to verify whether its a problem with Mono 6 or not.

**Comment by dan-christensen** [comment]
Yeah so it looks like all my markers are SVG's, the only PNG's are the airline logos and silhouettes on the right side bar. But if I recall, the PNG's on the side bar weren't showing either in the stable build.

**Comment by vradarserver** [comment]
I think this should be fixed with 2.4.5 preview 5. Let me know if it doesn't fix it.
