### ISSUE TITLE
Plugin unable to override IReceiverFormatManager interface

### ISSUE THREAD

**Issue by mill1000** [vradarserver/vrs#37]
A plugin is unable to override the `IReceiverFormatManager` (and `IRebroadcastFormatManager`) interface(s) as the plugin manager is resolved and loads the plugins after `IReceiverFormatManager` (and `IRebroadcastFormatManager`) is/are resolved.

I was attempting to write a plugin to support an additional received format via `IReceiverFormatManager` but that does not seem possible against the current version (v2.4.4).

**Comment by mill1000** [comment]
Scratch this. Jumped the gun. I see that I should be registering my provider by getting the ReceiverFormatManager with `Factory.ResolveSingleton<IReceiverFormatManager>()` and then calling `RegisterProvider`. 

Sorry for the noise.

**Comment by vradarserver** [comment]
No worries :) If you hit issues with adding formats via a plugin then do let me know, either here or in discussions.

**Comment by mill1000** [comment]
Thanks Andrew. If you don't mind I'd like to confirm that I'm on the right path. 

I can register a new `IReceiverFormatProvider` which will provide the `IMessageBytesExtractor` to pull useful data out of the (network) stream. Then, since the payload format is unique, I'll need to define a new IListener implementation to perform message translation/conversion of the extracted bytes into a BaseStationMessage.

Does this sound correct?

**Comment by vradarserver** [comment]
Sorry for the delay - I think the idea I had in mind was that if the feed that a plugin adds isn't already a Mode-S message then it would transcode it into a BaseStation format message and declare its format as `ExtractedBytesFormat`.`Port30003`. That can be done by:

1. Creating a `BaseStationMessage`, filling it in (making sure to set `MessageType` to `BaseStationMessageType`.`Transmission` and `TransmissionType` to any old non-zero value, `AllCallReply` would be fine).
2. Calling `ToBaseStationString(false)` to format the message as a string.
3. Calling `Encoding.ASCII.GetBytes()` to get the ASCII encoding of the message string.

... and then returning those bytes in the `ExtractedBytes` object with a format of `Port30003`.

However, on reflection that is a bit inefficient because VRS will then take the extracted bytes and reverse your steps to turn them back into a BaseStationMessage. All messages eventually end up as instances of BaseStationMessage. It would be better if you could return your BaseStationMessage directly and have the program just use what you give it.

I was thinking I could add a property called `BaseStationMessage` to `ExtractedBytes`. You would either fill in that property or `Bytes`, `Offset` and `Length`. There would be a separate `ExtractedBytesFormat` for providers that return ready-built BaseStation messages and it's that format that determines which property / properties VRS would expect to be filled in on the ExtractedBytes object.

On the face of it I don't think it would take too long to add in.
