### ISSUE TITLE
Aircraft not shown in combined feed when position is calculated with MLAT

### ISSUE THREAD

**Issue by ger-pakon** [vradarserver/vrs#43]
Hey,

according to [this forum post](https://forum.virtualradarserver.co.uk/viewtopic.php?f=9&t=2042) it seems so, that aircrafts will vanish in combined feed, when the positon of the aircraft is calculated with MLAT.

It's the only case I could verify so far.

If I choose the receiver (which "sees" the aircraft), the aircraft is visible.

Cheers and thank you very much,
Pakon

**Comment by dewoert** [comment]
Look like i have the same problem.
VRS 2.4.5 preview 4

**Comment by vradarserver** [comment]
Have you flagged the MLAT receiver as an MLAT receiver in the merged feed?

There is an issue with MLAT calculated positions in that there can be long pauses between each position update.

The way merged feeds work is that one receiver in the feed is considered the sole source for messages from a given aircraft. Messages from all other sources are ignored for that aircraft.

If the receiver doesn't pick up any messages from that aircraft for more than a few seconds (configurable, default is 3 seconds I think) then it stops being the source of messages, after which the first receiver that picks up a transmission from the aircraft becomes the new source.

If an MLAT receiver is only sending messages for the aircraft when it calculates a position then there can be long pauses between messages. If the pause is longer than three seconds then it'll most likely switch to another receiver that's reporting the non-position messages from the aircraft and you stop seeing the calculated positions.

There are two approaches that VRS takes to try to deal with this:

1. Some MLAT software will tag their calculated position messages that indicates that the position came from MLAT. If VRS sees those coming from a receiver on a merged feed, and if the elected receiver for that aircraft has never seen any position messages, then it will use the position from that MLAT message.
2. You can manually tag a receiver as an MLAT receiver in the merged feed, in which case all positions on that feed are assumed to be MLAT and are dealt with as per (1).

If your MLAT feed doesn't have the magic indicator on MLAT positions then you need to mark the receiver as an MLAT receiver when you set up the merged feed.

**Comment by antonov124** [comment]
How can we tag a receiver ?

**Comment by vradarserver** [comment]
Tools | Options | Merged Feeds. Select the merged feed, then select the MLAT receiver in the list and tick the MLAT box.

**Comment by antonov124** [comment]
thx

**Comment by antonov124** [comment]
So mlat is tagged,
but flight is not shown ;/

**Comment by marcus-aa** [comment]
Manually "tagging" a receiver as MLAT has never fully worked, targets from feeds manually set to mlat, but who lack "mlat magic timestamp" are still marked as mlat=no inside VRS if they are ONLY present on an mlat-set feed. Only when they are prioritized over another non-position feed data message are they actually marked as mlat=yes.

So, when viewing only the reciever from the mlat server, it will say mlat=no on ALL the targets, while infact 100% should be mlat=no, because they are then never merged before display.

MLAT status should be possible to be tagged on the receiver level , like "is satcom", not only in the merge process.

From an old thread in the forum

https://forum.virtualradarserver.co.uk/viewtopic.php?f=4&t=1209
