### ISSUE TITLE
Version3 Preview 6  Database Editor wont shown

### ISSUE THREAD

**Issue by antonov124** [vradarserver/vrs#44]
With the lastest Update Preview6 da Database Editor wont shown.  Back to Preview 3 Database Editor is back... 
(Dont have Preview 4/5)

Bug or Feature?!

**Comment by vradarserver** [comment]
I've just run v3 preview 6 on both Windows and Ubuntu and the database editor is working fine.

Bear in mind that you will need to install preview 6 of both the server and the plugin. The preview 3 plugin might be relying on things that are no longer present in preview 6.

**Comment by antonov124** [comment]
![db](https://user-images.githubusercontent.com/27861984/111871901-c6e11a80-898c-11eb-97fc-37acbedc95ca.JPG)
The Database Editor link is missing in the preview 6 , thats what i mean,   in  previous  versions its still there...

**Comment by vradarserver** [comment]
The editor link is there for me in preview 6, both under Windows and Linux / Mono.

Windows preview 6:

![image](https://user-images.githubusercontent.com/20142609/111874293-7669bd00-898c-11eb-80a4-6336fbd06a2e.png)

and Mono preview 6 running on Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/20142609/111875269-cea2be00-8990-11eb-8d2a-eedc4d6f79b8.png)

You are running custom content. Disable the custom content plugin and then refresh the page, if the link now appears then the custom content is the issue. Otherwise make sure that you have enabled the database editor plugin and installed the preview 6 version.

**Comment by antonov124** [comment]
the custom content has the issue,  with prev 3 its working, so do you have anything changed since prev3 to 6 in this section?

**Comment by vradarserver** [comment]
I have no control over your custom content, I have no way of knowing which change has broken it.

My guess - and it is only a guess - is that a custom script is expecting to see the airport data link and it is breaking when it's not there? It could be that that script runs before the database editor's script gets a chance to add its link to the page. When the custom script breaks it stops all scripts that run after it from initialising correctly.

I would start with having a look at the browser's console window for errors. Or alternatively disable each custom script one-by-one until the page loads correctly and then fix the script that you had to disable.
