### ISSUE TITLE
LocalAircraft file not working properly

### ISSUE THREAD

**Issue by BallerG** [vradarserver/vrs#81]
So I have a LocalAircraft .txt file which forces military aircraft such as 2-reg over to civil etc but on V3 I'm having issues getting it to work 

![Untitled](https://user-images.githubusercontent.com/64506538/189378037-147567b4-5215-4ad1-a52d-363c67a1ca49.jpg)
![Screenshot 2022-09-09 at 15-46-20 Virtual Radar (70)](https://user-images.githubusercontent.com/64506538/189378050-fdc1883b-1b14-4efa-acda-0589b6998e44.png)
![Untitled1](https://user-images.githubusercontent.com/64506538/189378302-1d30d91c-cb08-4255-aa3a-e1b443aa4740.jpg)

Do I need to do something different for V3?

**Comment by rikgale** [comment]
You either need to wait for the StandingData update which runs over night, or restart VRS.

Also selfless plug with instructions https://github.com/rikgale/LocalAircraft

**Comment by BallerG** [comment]
I have done both re waiting for the overnight update and a manual restart but neither have worked. 

Regarding the guide, that is exactly how I have the file named from Version 2.4.4

**Comment by rikgale** [comment]
They only thing I can suggest is trying a different LocalAircraft.txt and see if that works.

**Comment by vradarserver** [comment]
A bug had been introduced recently in the parsing of LocalAircraft.txt for v3. The unit tests already showed the bug, but I hadn't run the unit tests so that didn't help. Sorry about that! I've checked in the fix and it should appear in the next preview.

There is a larger problem in that the Guernsey registry's block post-dates the code blocks that VRS is using, it's entirely unaware of it and because it came out of a block that had previously been military you end up with all Guernsey registrations being shown as UK military.

I need to update the code blocks, but for that I'll need to find a source of them. I don't think the original source is still being updated.

**Comment by vradarserver** [comment]
Fixed in commit d2e0f13

**Comment by BallerG** [comment]
Thanks for the reply Andrew. I shall keep an eye out for the next release.
